default: build test
build:
	go build -v
install:
	go install -v
test:
	go test -v ./cli/...
	go test -v ./lib/...
	go test -v ./algorithms/...
	golint -set_exit_status ./cli/...
	golint -set_exit_status ./lib/...
	golint -set_exit_status ./algorithms/...
